### ISSUE TITLE
Cannt install by Community Plugins or BRAT

### ISSUE THREAD

**Issue by oldtowneast** [Automatt/pinboard-sync#3]
Says _"main.js is missing from the Release"_

![2022-01-25-15-38-44](https://user-images.githubusercontent.com/78783278/151064166-134427ab-d9ba-4af7-af53-ae6f10037d0e.png)
![2022-01-25-15-38-32](https://user-images.githubusercontent.com/78783278/151064168-b6fe921e-40bb-47dd-b52c-238050789bae.png)

**Comment by Yeshwanthyk** [comment]
Trying to install it through the community plugins. Having the same issue.

**Comment by anvimea** [comment]
Also cannot install via Community Plugins.

**Comment by danst0** [comment]
dito

**Comment by apolaine** [comment]
Same :-(

**Comment by Automatt** [comment]
Fixed install from community plugins.  Sorry about that!
