### ISSUE TITLE
'"authorUrl": "@automatt",' in manifest.json is not a URL

### ISSUE THREAD

**Issue by claremacrae** [Automatt/pinboard-sync#4]
Hi,

I'm just processing all the new plugins in to the Obsidian Hub, and noticed that your authorUrl isn't actually a URL:

https://github.com/Automatt/obsidian-pinboard-sync/blob/de4dbf3378a7a11b7c2ca0a615115f2023cb694a/manifest.json#L6

**Comment by Automatt** [comment]
Resolved, thanks!
